[bootstrap.packages]
# Ensure system packages are installed and update via
# > mise bootstrap packages apply
"brew:btop" = "latest"
"brew:fzf" = "latest"
"brew:lua-language-server" = "latest"
"brew:neovim" = "latest"
"brew:opencode" = "latest"
"brew:ripgrep" = "latest"
"brew:ruff" = "latest"
"brew:starship" = "latest"
"brew:uv" = "latest"
"brew-cask:bitwarden" = "latest"
"brew-cask:claude" = "latest"
"brew-cask:firefox" = "latest"
"brew-cask:ghostty" = "latest"
"brew-cask:gimp" = "latest"
"brew-cask:google-chrome" = "latest"
"brew-cask:google-drive" = "latest"
"brew-cask:inkscape" = "latest"
"brew-cask:notion" = "latest"
"brew-cask:rectangle" = "latest"
